# Generated by Django 5.1.6 on 2026-09-02 04:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('organiser', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('participation_role', models.CharField(choices=[('PRESENTER', 'Presenter'), ('ATTENDEE', 'Attendee'), ('ORGANISER', 'Organiser'), ('PANELLIST', 'Panellist')], default='ATTENDEE', max_length=12)),
                ('paper_title', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('abstract', models.TextField(blank=True)),
                ('research_area', models.CharField(blank=True, max_length=200)),
                ('funding_agency', models.CharField(blank=True, max_length=200)),
                ('funding_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On hold')], default='PROPOSED', max_length=12)),
                ('dataset_references', models.JSONField(blank=True, default=list)),
                ('ethics_approval_reference', models.CharField(blank=True, max_length=100)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborating_projects', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_projects', to='academics.department')),
                ('principal_investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_projects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed')], default='PENDING', max_length=15)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='research.researchproject')),
            ],
            options={
                'ordering': ['display_order', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=400)),
                ('authors', models.CharField(help_text='Comma-separated author list.', max_length=500)),
                ('venue', models.CharField(blank=True, help_text='Journal or conference name.', max_length=300)),
                ('publication_type', models.CharField(choices=[('JOURNAL', 'Journal article'), ('CONFERENCE', 'Conference paper'), ('BOOK', 'Book'), ('CHAPTER', 'Book chapter'), ('PREPRINT', 'Preprint'), ('REPORT', 'Technical report'), ('THESIS', 'Thesis')], default='JOURNAL', max_length=15)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=120)),
                ('url', models.URLField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('citation_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('ACCEPTED', 'Accepted'), ('PUBLISHED', 'Published')], default='PUBLISHED', max_length=15)),
                ('document', models.FileField(blank=True, null=True, upload_to='publications/%Y/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='research.researchproject')),
            ],
            options={
                'ordering': ['-year', 'title'],
                'indexes': [models.Index(fields=['owner', 'year'], name='research_pu_owner_i_a9ec83_idx')],
            },
        ),
    ]
