# Generated by Django 5.1.6 on 2026-09-02 04:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('FORTNIGHTLY', 'Fortnightly'), ('OFF', 'Off')], default='WEEKLY', max_length=12)),
                ('day_of_week', models.PositiveSmallIntegerField(default=0, help_text='0 = Monday')),
                ('send_email', models.BooleanField(default=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digest_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.CharField(choices=[('NEW_ASSIGNMENT', 'New assignment'), ('ASSIGNMENT_DEADLINE', 'Assignment deadline reminder'), ('ASSIGNMENT_GRADED', 'Assignment graded'), ('NEW_NOTE', 'New notes uploaded'), ('MARKS_PUBLISHED', 'Marks published'), ('ATTENDANCE_WARNING', 'Attendance warning'), ('ANNOUNCEMENT', 'Announcement'), ('EVENT_REMINDER', 'Event reminder'), ('MENTORSHIP_REQUEST', 'Mentorship request'), ('JOB_OPPORTUNITY', 'Job opportunity'), ('WEEKLY_DIGEST', 'Weekly digest'), ('FORUM_REPLY', 'Discussion reply'), ('ACCOUNT', 'Account and security')], max_length=30, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Supports {{placeholders}} such as {{student_name}}.')),
                ('email_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.CharField(choices=[('NEW_ASSIGNMENT', 'New assignment'), ('ASSIGNMENT_DEADLINE', 'Assignment deadline reminder'), ('ASSIGNMENT_GRADED', 'Assignment graded'), ('NEW_NOTE', 'New notes uploaded'), ('MARKS_PUBLISHED', 'Marks published'), ('ATTENDANCE_WARNING', 'Attendance warning'), ('ANNOUNCEMENT', 'Announcement'), ('EVENT_REMINDER', 'Event reminder'), ('MENTORSHIP_REQUEST', 'Mentorship request'), ('JOB_OPPORTUNITY', 'Job opportunity'), ('WEEKLY_DIGEST', 'Weekly digest'), ('FORUM_REPLY', 'Discussion reply'), ('ACCOUNT', 'Account and security')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_564b1f_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.CharField(choices=[('NEW_ASSIGNMENT', 'New assignment'), ('ASSIGNMENT_DEADLINE', 'Assignment deadline reminder'), ('ASSIGNMENT_GRADED', 'Assignment graded'), ('NEW_NOTE', 'New notes uploaded'), ('MARKS_PUBLISHED', 'Marks published'), ('ATTENDANCE_WARNING', 'Attendance warning'), ('ANNOUNCEMENT', 'Announcement'), ('EVENT_REMINDER', 'Event reminder'), ('MENTORSHIP_REQUEST', 'Mentorship request'), ('JOB_OPPORTUNITY', 'Job opportunity'), ('WEEKLY_DIGEST', 'Weekly digest'), ('FORUM_REPLY', 'Discussion reply'), ('ACCOUNT', 'Account and security')], max_length=30)),
                ('in_app', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=True)),
                ('push', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event'],
                'unique_together': {('user', 'event')},
            },
        ),
    ]
