# Generated by Django 5.1.6 on 2026-09-02 04:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('value', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('STRING', 'String'), ('NUMBER', 'Number'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON'), ('COLOR', 'Colour')], default='STRING', max_length=10)),
                ('group', models.CharField(choices=[('BRANDING', 'Branding'), ('ACADEMIC', 'Academic'), ('NOTIFICATION', 'Notifications'), ('SECURITY', 'Security'), ('UPLOAD', 'Uploads'), ('GENERAL', 'General')], default='GENERAL', max_length=15)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_public', models.BooleanField(default=False, help_text='Public settings are readable without authentication.')),
                ('is_editable', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['group', 'display_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('widget_key', models.SlugField(max_length=60)),
                ('label', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('DEAN', 'Dean'), ('ADMIN', 'HOD / Staff Admin'), ('FACULTY', 'Professor / Faculty'), ('SCHOLAR', 'Research Scholar'), ('STUDENT', 'Student'), ('ALUMNI', 'Alumni')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('column_span', models.PositiveSmallIntegerField(default=1)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'display_order'],
                'unique_together': {('widget_key', 'role')},
            },
        ),
    ]
