# Generated by Django 5.1.6 on 2026-09-02 04:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.EmailField(blank=True, help_text='Retained if the user is later removed.', max_length=254)),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAILED', 'Failed login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password change'), ('PASSWORD_RESET', 'Password reset'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('ROLE_CHANGE', 'Role change'), ('MARKS_CHANGE', 'Marks modification'), ('MARKS_PUBLISH', 'Marks published'), ('ATTENDANCE_CHANGE', 'Attendance modification'), ('FILE_UPLOAD', 'File upload'), ('FILE_DELETE', 'File deletion'), ('EXPORT', 'Data export'), ('PERMISSION_DENIED', 'Permission denied'), ('SETTINGS_CHANGE', 'Settings change')], db_index=True, max_length=25)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=80)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('object_label', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'created_at'], name='auditlogs_a_actor_i_a6eeb4_idx'), models.Index(fields=['action', 'created_at'], name='auditlogs_a_action_8e4047_idx')],
            },
        ),
    ]
