# Generated by Django 5.1.6 on 2026-09-02 04:29

import apps.certificates.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_id', models.CharField(db_index=True, default=apps.certificates.models.generate_certificate_id, max_length=30, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('certificate_type', models.CharField(choices=[('PARTICIPATION', 'Participation'), ('COMPLETION', 'Course completion'), ('INTERNSHIP', 'Internship'), ('WORKSHOP', 'Workshop'), ('MERIT', 'Merit'), ('BONAFIDE', 'Bonafide')], default='PARTICIPATION', max_length=15)),
                ('issued_on', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='certificates/%Y/')),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('REVOKED', 'Revoked')], default='ISSUED', max_length=10)),
                ('revoked_reason', models.CharField(blank=True, max_length=250)),
                ('verification_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('issuing_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='academics.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_on'],
            },
        ),
    ]
