# Generated by Django 5.1.6 on 2026-09-02 04:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('QUIZ', 'Quiz'), ('ATTENDANCE', 'Attendance'), ('SEMINAR', 'Seminar'), ('PRESENTATION', 'Presentation'), ('MIDTERM', 'Mid-term'), ('PROJECT', 'Project'), ('PRACTICAL', 'Practical'), ('VIVA', 'Viva'), ('OTHER', 'Other')], default='ASSIGNMENT', max_length=20)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight', models.DecimalField(decimal_places=2, default=10, help_text='Contribution to the internal total, in marks.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_auto_calculated', models.BooleanField(default=False, help_text='Derived from attendance or assignment data instead of manual entry.')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_components', to='courses.coursesection')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('section', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to='academics.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComponentScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_absent', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for review'), ('REVIEWED', 'Reviewed'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assessments.assessmentcomponent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_scores', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_scores', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student__full_name'],
                'indexes': [models.Index(fields=['student', 'status'], name='assessments_student_6b22f5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('marks_obtained__gte', 0), ('marks_obtained__isnull', True), _connector='OR'), name='component_score_non_negative')],
                'unique_together': {('component', 'student')},
            },
        ),
        migrations.CreateModel(
            name='CourseResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('internal_total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('internal_max', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('external_total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('external_max', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grade_letter', models.CharField(blank=True, max_length=5)),
                ('grade_point', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('credits', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('is_pass', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='courses.coursesection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_results', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student__full_name'],
                'indexes': [models.Index(fields=['section', 'is_published'], name='assessments_section_c9dba2_idx')],
                'unique_together': {('student', 'section')},
            },
        ),
        migrations.CreateModel(
            name='ExternalMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('THEORY', 'University theory'), ('PRACTICAL', 'Practical'), ('VIVA', 'Viva'), ('PROJECT', 'Project')], default='THEORY', max_length=15)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=12)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_marks', to='courses.coursesection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_marks', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student__full_name'],
                'unique_together': {('student', 'section', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='GradeBand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('letter', models.CharField(max_length=5)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('grade_point', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('is_pass', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='assessments.gradescale')),
            ],
            options={
                'ordering': ['-min_percentage'],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_percentage__gte', models.F('min_percentage'))), name='grade_band_range_valid')],
                'unique_together': {('scale', 'letter')},
            },
        ),
    ]
