#!/usr/bin/env bash
#
# One-shot setup for a fresh Ubuntu EC2 / Lightsail instance.
#
#   curl -fsSL https://raw.githubusercontent.com/Rikdebmandal/SRMIST-Public-Health-LMS/main/scripts/aws-bootstrap.sh | bash
#
# Installs Docker, adds swap if memory is tight, clones the repo, generates
# secrets, detects the instance's public IP, then brings the stack up on
# port 80 and seeds the demonstration data.
#
# Re-running it is safe: it skips work that is already done.

set -euo pipefail

REPO_URL="https://github.com/Rikdebmandal/SRMIST-Public-Health-LMS.git"
APP_DIR="$HOME/SRMIST-Public-Health-LMS"

log()  { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m    %s\033[0m\n' "$*"; }
die()  { printf '\n\033[1;31mFAILED: %s\033[0m\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
log "Checking the machine"
TOTAL_MB=$(awk '/MemTotal/ {print int($2/1024)}' /proc/meminfo)
echo "    RAM: ${TOTAL_MB} MB"

# The Next.js build needs roughly 2 GB. Free-tier instances have 1 GB, so add
# swap rather than letting the build get OOM-killed halfway through.
if [ "$TOTAL_MB" -lt 2048 ] && [ ! -f /swapfile ]; then
    log "Adding 2 GB swap (needed for the frontend build on a small instance)"
    sudo fallocate -l 2G /swapfile
    sudo chmod 600 /swapfile
    sudo mkswap /swapfile >/dev/null
    sudo swapon /swapfile
    echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab >/dev/null
    echo "    swap active"
fi

# ---------------------------------------------------------------------------
log "Installing Docker"
if command -v docker >/dev/null 2>&1; then
    echo "    already installed"
else
    sudo apt-get update -qq
    sudo apt-get install -y -qq git curl >/dev/null
    curl -fsSL https://get.docker.com | sudo sh >/dev/null 2>&1
    sudo usermod -aG docker "$USER"
    echo "    installed"
fi

# The group change does not apply to this shell, so use sudo for compose here.
DC="sudo docker compose"

# ---------------------------------------------------------------------------
log "Fetching the code"
if [ -d "$APP_DIR/.git" ]; then
    git -C "$APP_DIR" pull --ff-only
    echo "    updated"
else
    git clone --depth 1 "$REPO_URL" "$APP_DIR"
    echo "    cloned"
fi
cd "$APP_DIR"

# ---------------------------------------------------------------------------
log "Detecting the public address"
# IMDSv2 first (required on newer instances), then fall back.
TOKEN=$(curl -fsS -X PUT "http://169.254.169.254/latest/api/token" \
        -H "X-aws-ec2-metadata-token-ttl-seconds: 60" --max-time 3 2>/dev/null || true)
if [ -n "$TOKEN" ]; then
    PUBLIC_IP=$(curl -fsS -H "X-aws-ec2-metadata-token: $TOKEN" \
                --max-time 3 http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || true)
fi
PUBLIC_IP="${PUBLIC_IP:-$(curl -fsS --max-time 5 https://api.ipify.org 2>/dev/null || true)}"
[ -n "$PUBLIC_IP" ] || die "Could not determine the public IP. Set it by hand in .env."
echo "    $PUBLIC_IP"

# ---------------------------------------------------------------------------
log "Writing configuration"
if [ -f .env ]; then
    warn ".env already exists - leaving it alone"
else
    SECRET=$(head -c 64 /dev/urandom | base64 | tr -d '/+=' | head -c 64)
    DB_PASS=$(head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 32)

    cat > .env <<EOF
# Generated by aws-bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
DJANGO_SECRET_KEY=${SECRET}
DJANGO_DEBUG=false
DJANGO_ALLOWED_HOSTS=${PUBLIC_IP},localhost,127.0.0.1,backend

POSTGRES_DB=public_health_lms
POSTGRES_USER=phlms
POSTGRES_PASSWORD=${DB_PASS}

# One origin for the API and the app, so the refresh cookie stays same-site.
NEXT_PUBLIC_API_URL=http://${PUBLIC_IP}
FRONTEND_BASE_URL=http://${PUBLIC_IP}
CORS_ALLOWED_ORIGINS=http://${PUBLIC_IP}
CSRF_TRUSTED_ORIGINS=http://${PUBLIC_IP}

# No certificate yet - forcing HTTPS would make the site unreachable.
SECURE_SSL_REDIRECT=false
REFRESH_COOKIE_SECURE=false
REFRESH_COOKIE_SAMESITE=Lax

REDIS_URL=redis://redis:6379/0
CELERY_BROKER_URL=redis://redis:6379/0
CELERY_RESULT_BACKEND=redis://redis:6379/1

TIME_ZONE=Asia/Kolkata
LOG_LEVEL=INFO
EOF
    chmod 600 .env
    echo "    .env written with generated secrets"
fi

# ---------------------------------------------------------------------------
log "Building and starting (first run takes 5-10 minutes)"
$DC -f docker-compose.yml -f docker-compose.http.yml up -d --build

# ---------------------------------------------------------------------------
log "Waiting for the API"
for _ in $(seq 1 60); do
    if curl -fsS --max-time 3 "http://localhost/api/v1/health" >/dev/null 2>&1; then
        echo "    healthy"
        break
    fi
    sleep 5
done

curl -fsS --max-time 5 "http://localhost/api/v1/health" >/dev/null 2>&1 \
    || die "API did not come up. Check: sudo docker compose logs backend"

# ---------------------------------------------------------------------------
log "Seeding demonstration data"
if $DC exec -T backend python manage.py seed_demo --reset >/dev/null 2>&1; then
    echo "    seeded"
else
    warn "Seeding failed - run it by hand:"
    warn "  sudo docker compose exec backend python manage.py seed_demo --reset"
fi

# ---------------------------------------------------------------------------
cat <<EOF

============================================================
  Public Health LMS is running

  URL       http://${PUBLIC_IP}
  API docs  http://${PUBLIC_IP}/api/docs/

  Demonstration sign-in (password: Demo@12345)
    Student   student1@sph.srmist.demo
    Faculty   faculty1@sph.srmist.demo
    HOD       hod@sph.srmist.demo
    Dean      dean@sph.srmist.demo
============================================================

  If the page does not load, open port 80 in the security group.

  This is plain HTTP. Anyone on the network path can read the
  session token. Add a domain and TLS before using real data:
    docs/AWS.md, "Issue the certificate"

  The demo password is public, so treat everything here as
  world-readable. Do not seed a deployment that holds real records.

  Useful commands:
    sudo docker compose logs -f backend
    sudo docker compose -f docker-compose.yml -f docker-compose.http.yml restart
    sudo docker compose down

EOF
